import { CommonModule } from '@angular/common';
import { Component, input } from '@angular/core';

@Component({
  selector: 'eco-icon',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './icon.component.html',
  styleUrl: './icon.component.scss',
})
export class IconComponent {
  icon = input.required<EcoIcon>();
}

export const ECO_ICONS = [
  'file-paper',
  'add-people',
  'in-progress',
  'key',
  'line-chart',
  'link',
  'starts',
  'envelope',
  'in-preparation',
  'm2',
  'guard',
  'playlist-add',
  'cancel',
  'upload',
  'circle',
  'declined',
  'next-page',
  'last-page',
  'previous-page',
  'first-page',
  'task-complete',
  'event',
  'search',
  'ruler',
  'rounded-info',
  'rounded-correct',
  'rounded-arrow-up',
  'pulse',
  'pin',
  'person',
  'notifications',
  'layers',
  'hour-arrow',
  'hour',
  'gps',
  'full-screen',
  'file',
  'eye',
  'export',
  'edit-outline',
  'edit',
  'delete',
  'data',
  'cycle',
  'correct',
  'columns',
  'calendar',
  'bar-chart',
  'arrow-down',
  'access-alarm',
  'overlay',
  'zoom-out',
  'zoom-in',
  'warrning-sign',
  'warrning',
  'video-camera',
  'upload-file',
  'unknown-document',
  'tune',
  'trending-up',
  'tree',
  'text-snippet',
  'storage',
  'servers',
  'view-agenda',
  'solving-cases',
  'codetables',
  'blocked',
  'logout',
  'back',
  'change-password',
] as const;

export type EcoIcon = (typeof ECO_ICONS)[number];
